global:
    api_version: 1
    database: 'tormenta.db'
agent:
  enabled: True
  listen: 'http://0.0.0.0:8080'
  tracker:   [  
  "http://localhost:8090" 
  ]
  resources:
    disk:
      limit: 4096
      path: '/images'
    cpu: 
      limit: 
        cores: 3
    swap:
      limit: 1024
    memory:
      limit: 1024
    network:
      limit:
        in: 1024
        out: 1024
tracker:
  enabled: True
  listen: 'http://0.0.0.0:8090'