node:
        tracker:   [  "master.node.pyrosome.org:5392" ]

        key: '/home/user/public.key'

        rest:
            port: 8080
            notifications: true
            token: true

        database:
            uri: 'tormenta.db'
resources:

        disk:
            limit: 4096
            type: 'lvm | image'
            lvm: 
                volume: 'vol01'
            image:
                path: '/images'

        cpu: 
            cores: [ 0, 1, 2 ]
            limit:
                    shares: 2048

        swap:
            limit: 1024

        memory:
            limit: 1024

        network:
            limit:
                in: 1024
                out: 1024
